# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: .venv/bin/ruff
        language: system
        args: [check, --fix]
        types: [python]
      - id: ruff-format
        name: ruff-format
        entry: .venv/bin/ruff
        language: system
        args: [format]
        types: [python]
      - id: mypy
        name: mypy
        entry: .venv/bin/mypy
        language: system
        args: [--strict]
        types: [python]
